blank_issues_enabled: false
contact_links:
  - name: Libera.Chat
    url: https://librea.chat/
    about: On here, talk to Tommy on the channel #tommyprojects.
  - name: OSFirstTimer
    url: https://www.youtube.com/osfirsttimer
    about: You can't see Tommy without OSFirstTimer!
