blank_issues_enabled: false
contact_links:
  - name: Libera.Chat
    url: https://librea.chat/
    about: On here, talk to Tommy on the channel #tommyprojects
  - name: Community email through Mailinator, go to mailinator.com to respond to emails.
    url: mailto:tommychatbotemails@mailinator
